#!/usr/bin/python


import argparse, os, sys


if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('--ctf', required=True, help='The CTF name.')
    parser.add_argument('--challenge', required=True, help='The challenge name')
    args = parser.parse_args(sys.argv[1:])

    ctf_name=args.ctf
    chal_name=args.challenge
    root_dir=os.path.dirname(os.path.realpath(__file__))
    shared_dir=os.path.join(root_dir, 'shared')
    chal_dir=os.path.join(root_dir, ctf_name, chal_name)

    os.makedirs(chal_dir)
    os.symlink(os.path.relpath(shared_dir, chal_dir),
               os.path.join(chal_dir, 'shared'))


# vim: set filetype=python :
